header
Rukovich/v-pitere-pivo pull request #1
Opened 2022-11-15 18:57 UTC by Rukovich

2022-11-15 20:08 UTC, andrey-kudinov requested changes
Хороший старт
Есть несколько замечаний по коду, посмотри пж
Так же добавь пж для деплоя Netlify

2022-11-15 20:08 UTC, andrey-kudinov commented on src/scss/_header.scss
> +    z-index: -1;
Лучше не использовать отрицательный z-index
Просто повысь до 2 z-index у элементов, который должны быть сверху

2022-11-15 20:08 UTC, andrey-kudinov commented on src/js/header.js
> +let navWrapper = document.querySelector(".nav__wrapper");
Используй лучше всегда **const** если по коду не требуется обратного

2022-11-15 20:08 UTC, andrey-kudinov commented on src/scss/vars.scss
> +  font-family: Patsy Sans;
По логике файл называется vars и тут должны быть переменные

2022-11-15 20:08 UTC, andrey-kudinov commented on src/scss/_header.scss
> +    font-size: 15px;
Есть много мнений, но достаточно логично придерживаться концепции:
 - для всего что связано с шрифтами использовать rem
 - для всего остального пиксели

Я устно расскажу агрументы потом
Пока что с самого начала можно придерживаться такой практики

2022-11-16 16:56 UTC, Rukovich commented
поправил до чего дотянулся, но баг со шторкой починить не получилось.
[деплой](https://v-pitere-pivo.netlify.app)

2022-11-16 17:04 UTC, andrey-kudinov approved these changes
В целом всё хорошо
Но некоторые архитектурные моменты можно обсудить

2022-11-16 17:04 UTC, andrey-kudinov commented on src/scss/_header.scss
> +  padding: 1rem 1rem;
Можно сокращенный синтаксис
padding: 1rem

2022-11-16 17:04 UTC, andrey-kudinov commented on src/js/header.js
> +
Лишняя пустая строчка

2022-11-16 17:04 UTC, andrey-kudinov commented on src/scss/_header.scss
> +      top: 1rem;
Можно все в ремах
Как вариант можно только шрифты в ремах, а все остальное в пикселях

2022-11-16 17:04 UTC, andrey-kudinov commented on src/scss/_header.scss
> +      top: 1rem;
Можем такую концепцию в тг обсудить

2022-11-16 17:16 UTC, Rukovich commented
поправил на пиксели

2022-11-16 17:47 UTC, merged