Dev06 js
Rukovich/v-pitere-pivo pull request #7
Opened 2022-11-22 18:38 UTC by Rukovich

2022-11-22 18:55 UTC, andrey-kudinov requested changes
Здесь есть несколько комментариев
Я пока не вижу почему не работает
Надо дебажить

2022-11-22 18:55 UTC, andrey-kudinov commented on src/js/tabClick.js
> +const dataBeer ='[data-tab=beer]';
"beer" тоже в ковычках

2022-11-22 18:55 UTC, andrey-kudinov commented on src/js/tabClick.js
> +    document.querySelector(`${dataNav}`).classList.add('tabs__caption_active');
Можно просто dataNav без кавычек
Это уже строка

2022-11-22 18:55 UTC, andrey-kudinov commented on src/js/tabClick.js
> +const beerClick = document.querySelector('#beerClick');
Нейминг сложная тема всегда
Я думаю здесь стоит подобрать другие названия переменных

2022-11-22 18:55 UTC, andrey-kudinov commented on src/js/tabClick.js
> +function clickNavigation(navClick, dataNav) {
Здесь я бы тоже ещё раз подумал бы над неймингом

2022-11-23 13:17 UTC, Rukovich commented on src/js/tabClick.js
> +const dataBeer ='[data-tab=beer]';
исправил

2022-11-23 13:17 UTC, Rukovich commented on src/js/tabClick.js
> +    document.querySelector(`${dataNav}`).classList.add('tabs__caption_active');
исправил

2022-11-23 13:33 UTC, Rukovich commented
Поправил замечания, над неймингом еще поработать придется

2022-11-23 13:42 UTC, merged